version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - gocyclo
    - gosec
    - misspell
    - mnd
    - noctx
    - unparam
    - wastedassign
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
