app:
  name: "innopolis"
  environment: "local"
  port: "8080" 
  debug: true

log:
  level: "debug"
  style: "yaml" # формат логов - yaml
  file: "" #test укажите путь к файлу для хранения логов

postgres:
  host: "localhost"
  port: 5432
  username: "username"
  password: "user_password"
  dbname: "db_name"

minio:
  endpoint: "localhost:9000"
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
  bucketName: "your-bucket"
  region: "us-east-1"
  useSSL: false

