app:
  name: "innopolis"
  environment: "prod"
  port: "" #test
  debug: false

log:
  level: "info"
  style: "yaml" # формат логов - yaml
  file: "" #test укажите путь к файлу для хранения логов

postgres:
  host: "prod-db-host"
  port: "" #test
  user: "username"
  password: "user_password"
  dbname: "db_name"

minio:
  endpoint: "prod-minio.example.com:9000"
  accessKeyID: ""
  secretAccessKey: ""
  bucketName: "prod-bucket"
  region: "us-east-1"
  useSSL: true