version: "3.9"

services:
  tg-bot:
    build:
      context: .
    container_name: tg-bot
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ./main

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      PG_USER: postgres_user
      PG_PASSWORD: postgres_password
      PG_DB: postgres_db
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web UI
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    env_file:
      - .env
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
  minio_data:
