app:
  name: "innopolis"
  environment: "local"
  port: "8080" 
  debug: true

log:
  level: "debug"
  style: "yaml" # формат логов - yaml
  file: "" # укажите путь к файлу для хранения логов

postgres:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  dbname: "innopolis"

minio:
  endpoint: "localhost:9000"
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
  bucketName: "innopolis"
  region: "us-east-1"
  useSSL: false 